name: Deploy to EC2

on:
  push:
    branches:
      - master  # Sirf main branch push pe deploy hoga

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # GitHub repo ka code pull karega

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Node.js install karega agar nahi hai
            if ! command -v node &> /dev/null
            then
                echo "Installing Node.js..."
                curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                sudo apt install -y nodejs
            fi

            # PM2 install karega agar nahi hai
            if ! command -v pm2 &> /dev/null
            then
                echo "Installing PM2..."
                sudo npm install -g pm2
            fi

            # Deploy the Node.js app
            cd cicd  # Apni app ka path set karo
            git pull origin master    # Latest code pull karega
            npm install             # Dependencies install karega
            pm2 restart index.js "app" || pm2 start index.js --name "app"  # App restart ya start karega


            # pm2 save
            # pm2 startup
